# Generated by Django 5.2.7 on 2025-11-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("main_info", models.TextField(verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(upload_to="media/", verbose_name="Превью"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("publication_attribute", models.BooleanField(verbose_name="Признак")),
                ("viewers", models.IntegerField(verbose_name="кол-во просмотров")),
            ],
            options={
                "verbose_name": "публикация",
                "verbose_name_plural": "публикации",
                "ordering": ["heading"],
            },
        ),
    ]
