# Generated by Django 5.2.8 on 2025-12-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('main_info', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(default='record/Pes_shakal.jpg', upload_to='record/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication_attribute', models.BooleanField(default=True, verbose_name='Признак')),
                ('viewers', models.IntegerField(default=0, verbose_name='кол-во просмотров')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ['heading'],
            },
        ),
    ]
