# Generated by Django 5.2.7 on 2025-11-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="preview",
            field=models.ImageField(upload_to="record/", verbose_name="Превью"),
        ),
    ]
