# Generated by Django 5.2.7 on 2025-11-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_alter_record_viewers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="viewers",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="кол-во просмотров"
            ),
        ),
    ]
