# Generated by Django 5.2.7 on 2025-11-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0006_alter_record_viewers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="viewers",
            field=models.IntegerField(default=0, verbose_name="кол-во просмотров"),
        ),
    ]
