# Generated by Django 5.2.7 on 2025-11-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0007_alter_record_viewers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="publication_attribute",
            field=models.BooleanField(default=True, verbose_name="Признак"),
        ),
    ]
