# Generated by Django 5.2.7 on 2025-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0008_alter_record_publication_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="preview",
            field=models.ImageField(
                default="record/Pes_shakal.jpg",
                upload_to="record/",
                verbose_name="Превью",
            ),
        ),
    ]
